# Generated by Django 5.0.6 on 2024-06-24 10:09

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikiproject', '0002_userprofile_git_link_userprofile_linledin_link_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
